"""empty message

Revision ID: c917541e7f34
Revises: d705462936b4
Create Date: 2023-11-15 11:27:15.834430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c917541e7f34'
down_revision = 'd705462936b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('hp', sa.String(), nullable=False),
    sa.Column('att', sa.String(), nullable=False),
    sa.Column('df', sa.String(), nullable=False),
    sa.Column('date_pokemon_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('username')

    op.drop_table('pokemon')
    # ### end Alembic commands ###
